services:
  app:
    build: .
    volumes:
      - ./app:/app
      - ./extracts:/extracts
    working_dir: /app
    command: tail -f
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=reporting
      - DB_USER=root
      - DB_PASSWORD=root-pw
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root-pw
      POSTGRES_DB: reporting
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql